name: Publish package to the Maven Central Repository
on:
  release:
    types: [prereleased]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE_BASE64: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE_BASE64 }}
        run: |
          echo $SIGNING_SECRET_KEY_RING_FILE_BASE64 | base64 --decode > ./secring.gpg
          ./gradlew publish \
          -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_TOKEN \
          -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD \
          -Psigning.secretKeyRingFile=./secring.gpg
