name: CI

on: [pull_request]

jobs:
  run_test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Test
        run: ./gradlew test
      - name: Build sample app
        run: ./gradlew sample:build
